### ISSUE TITLE
Get logged in userid and save it somewhere that actions.js can get it

### ISSUE THREAD

**Issue by nwself** [JMU-CIME/CPR-Music#7]
Then fix hardcoded userid in the create enrollment for owner here: https://github.com/JMU-CIME/CPR-Music/blob/107b6bf324b47795f6f3cdd463eac40c35a29df7/actions.js#L55

And also add `owner: loggedInUserID` to create course post here: https://github.com/JMU-CIME/CPR-Music/blob/107b6bf324b47795f6f3cdd463eac40c35a29df7/actions.js#L24

**Comment by hcientist** [comment]
fixed by c7934b49d7541e3dedd5778c39fccb4946dcd07c
